remote_theme: MicrosoftLearning/Jekyll-Theme
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: FelipePorcinoProfessor
twitter_username: mslearning
github_username: FelipePorcinoProfessor
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: GFM
title: Labs de Multi-Agentes com Microsoft Foundry
